spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SmartNote
    password: Larry123
    username: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
